language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails5.0.1_protobuf.gemfile
  - gemfiles/rails5.0.1_ruby_protobuf.gemfile
  - gemfiles/rails5.1.3_protobuf.gemfile
  - gemfiles/rails5.1.3_ruby_protobuf.gemfile
  - gemfiles/rails5.2.4.4_protobuf.gemfile
  - gemfiles/rails5.2.4.4_ruby_protobuf.gemfile
  - gemfiles/rails6.0.3.4_protobuf.gemfile
  - gemfiles/rails6.0.3.4_ruby_protobuf.gemfile
  - gemfiles/rails6.1.0_protobuf.gemfile
  - gemfiles/rails6.1.0_ruby_protobuf.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 6bdbd657ebc3097c1ca86672a45b6408a457a5d80cea234937f4d4adfbf004bd
